// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUObCf_tc5V_z7K5HOB74inoaUzEWn8cc',
    appId: '1:727500225899:web:a4e69ecdef8bc63081602e',
    messagingSenderId: '727500225899',
    projectId: 'udemy-course11',
    authDomain: 'udemy-course11.firebaseapp.com',
    storageBucket: 'udemy-course11.appspot.com',
    measurementId: 'G-1NX22H4Y1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz6wg0tV1fBJr9VElOwh1UNa7Vmywpc_0',
    appId: '1:727500225899:android:f0464a3515fb7d4f81602e',
    messagingSenderId: '727500225899',
    projectId: 'udemy-course11',
    storageBucket: 'udemy-course11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoWaLNXB_cp0jynYpjlm9UY-l4bpyQwg',
    appId: '1:727500225899:ios:61906924e21cf11c81602e',
    messagingSenderId: '727500225899',
    projectId: 'udemy-course11',
    storageBucket: 'udemy-course11.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
